### PR TITLE
Added depends.txt and waterplus support: drops waterplus:finite_1 when it rains

### PR DESCRIPTION
**Pull request by sloantothebone**

### CODE REVIEW

**Comment by Jeija** [comment]
Untested, but looks ok. I'm glad if you'd like to maintain this mod, I don't have the time for it.
Could you please rebase all your commits into one? Once you do that, I will merge this PR.

**Comment by sloantothebone** [comment]
How do I do that? and I must look around for an alternative to waterplus, so don't pull this. I'm also working on a weather.conf file and perhaps a wildcard weather where you define the .png and the nodes dropped in the .conf

**Comment by Jeija** [comment]
This is a great short article that explains how to rebase commits: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

Also, please clean your code up! (no `print("Lol print works") `, broken code etc). If there is code in there that is commented out because it doesn't work or is somehow dead, remove it.

One more thing: Please make a space after the two `--` for comments, such as `-- this is a comment`, not `--this is a comment`

**Comment by theFox6** [comment]
could you please resolve the conflicts?

**Pull request closed without merging**
